/**
 * Razorpay Payment Verify Endpoint
 * Mount at: /api/razorpay/verify
 *
 * Flow:
 *  1. Receive razorpay_payment_id, razorpay_order_id, razorpay_signature, booking_id
 *  2. Verify HMAC-SHA256 signature server-side
 *  3. Call confirmBookingAfterPayment (gateway-agnostic, idempotent)
 *  4. Return success
 *
 * Security:
 *  - RAZORPAY_KEY_SECRET never exposed to frontend
 *  - Uses service role key for Supabase (server-only)
 */

// @ts-expect-error: createAPIFileRoute is dynamically generated by TanStack Start
import { createAPIFileRoute } from "@tanstack/react-start/api";
import { createClient, SupabaseClient } from "@supabase/supabase-js";
import { createHmac } from "crypto";
import { confirmBookingAfterPayment } from "@/lib/booking-api";
import { sendBookingConfirmationEmail } from "@/lib/email";

const supabaseAdmin = createClient(
  process.env.VITE_SUPABASE_URL ?? "",
  process.env.SUPABASE_SERVICE_ROLE_KEY ?? "",
);

export const APIRoute = createAPIFileRoute("/api/razorpay/verify")({
  POST: async ({ request }) => {
    try {
      const body = await request.json();
      const { razorpay_payment_id, razorpay_order_id, razorpay_signature, booking_id } = body;

      if (!razorpay_payment_id || !razorpay_order_id || !razorpay_signature || !booking_id) {
        return new Response(JSON.stringify({ success: false, error: "Missing required fields" }), {
          status: 400,
          headers: { "Content-Type": "application/json" },
        });
      }

      // ── 1. Verify Razorpay HMAC-SHA256 signature ─────────────────────────
      const expectedSignature = createHmac("sha256", process.env.RAZORPAY_KEY_SECRET ?? "")
        .update(`${razorpay_order_id}|${razorpay_payment_id}`)
        .digest("hex");

      if (expectedSignature !== razorpay_signature) {
        console.error("[Razorpay Verify] ❌ Invalid signature for booking:", booking_id);
        return new Response(
          JSON.stringify({ success: false, error: "Invalid payment signature" }),
          { status: 401, headers: { "Content-Type": "application/json" } },
        );
      }

      console.log("[Razorpay Verify] ✅ Signature valid for booking:", booking_id);

      // ── 2. Fetch booking to get amount ────────────────────────────────────
      const { data: booking, error: fetchErr } = await supabaseAdmin
        .from("bookings")
        .select("id, booking_id, booking_status, customer_id, total_amount, amount_paid")
        .eq("id", booking_id)
        .single();

      if (fetchErr || !booking) {
        console.error("[Razorpay Verify] Booking not found:", booking_id);
        return new Response(JSON.stringify({ success: false, error: "Booking not found" }), {
          status: 404,
          headers: { "Content-Type": "application/json" },
        });
      }

      // ── 3. Confirm booking (idempotent via confirmBookingAfterPayment) ────
      await confirmBookingAfterPayment(
        {
          bookingId: booking.id,
          orderId: razorpay_order_id,
          paymentId: razorpay_payment_id,
          signature: razorpay_signature,
          amountPaid: booking.total_amount ?? 0,
          gateway: "razorpay",
          gatewayResponse: body,
        },
        supabaseAdmin as unknown as SupabaseClient,
      );

      console.log("[Razorpay Verify] ✅ Booking confirmed:", booking.booking_id);

      // ── 4. Fire-and-forget email confirmation ─────────────────────────────
      if (booking.customer_id) {
        const { data: customer } = await supabaseAdmin
          .from("customers")
          .select("name, email, phone")
          .eq("id", booking.customer_id)
          .single();

        if (customer?.email) {
          sendBookingConfirmationEmail({
            customerName: customer.name,
            customerEmail: customer.email,
            bookingId: booking.booking_id ?? booking.id,
            amountPaid: booking.total_amount ?? 0,
          }).catch((err) => console.error("[Razorpay Verify] Email failed:", err));
        }
      }

      return new Response(JSON.stringify({ success: true, bookingId: booking.id }), {
        status: 200,
        headers: { "Content-Type": "application/json" },
      });
    } catch (err: unknown) {
      const errMsg = err instanceof Error ? err.message : "Unknown error";
      console.error("[Razorpay Verify] Unexpected error:", err);
      return new Response(JSON.stringify({ success: false, error: errMsg }), {
        status: 500,
        headers: { "Content-Type": "application/json" },
      });
    }
  },
});
