/**
 * Razorpay Webhook Handler
 * Mount at: /api/razorpay/webhook
 *
 * Configure this URL in your Razorpay Dashboard → Webhooks.
 *
 * Events handled:
 *   payment.authorized  → confirms booking (Razorpay auto-captured or manual)
 *   order.paid          → confirms booking (order fully paid)
 *   payment.captured    → confirms booking (capture event after authorization)
 *   payment.failed      → marks booking PENDING/FAILED, restores seats
 *   refund.created      → logs refund, updates payment record
 *   refund.processed    → marks refund complete, updates booking/customer records
 *
 * Security:
 *   - Verifies x-razorpay-signature using HMAC-SHA256 + RAZORPAY_KEY_SECRET
 *   - Uses supabaseAdmin (service role) — server-only
 *   - confirmBookingAfterPayment is idempotent (skips if already CONFIRMED)
 *   - Always returns 200 so Razorpay stops retrying
 */

// @ts-expect-error: createAPIFileRoute is dynamically generated by TanStack Start
import { createAPIFileRoute } from "@tanstack/react-start/api";
import { createClient, SupabaseClient } from "@supabase/supabase-js";
import { createHmac } from "crypto";
import { confirmBookingAfterPayment } from "@/lib/booking-api";
import { sendBookingConfirmationEmail } from "@/lib/email";

const supabaseAdmin = createClient(
  process.env.VITE_SUPABASE_URL ?? "",
  process.env.SUPABASE_SERVICE_ROLE_KEY ?? "",
);

interface RazorpayWebhookBody {
  event: string;
  payload?: {
    payment?: {
      entity?: {
        id?: string;
        amount?: number;
        currency?: string;
        order_id?: string;
        error_description?: string;
      };
    };
    order?: {
      entity?: {
        id?: string;
        amount?: number;
        currency?: string;
        order_id?: string;
      };
    };
    refund?: {
      entity?: {
        id?: string;
        amount?: number;
        payment_id?: string;
      };
    };
  };
}

export const APIRoute = createAPIFileRoute("/api/razorpay/webhook")({
  POST: async ({ request }) => {
    try {
      const rawBody = await request.text();

      // ── 1. Verify Razorpay Webhook Signature ─────────────────────────────
      const receivedSignature = request.headers.get("x-razorpay-signature");
      if (!receivedSignature) {
        console.error("[Razorpay Webhook] Missing x-razorpay-signature header");
        return new Response("Missing signature", { status: 401 });
      }

      const expectedSignature = createHmac("sha256", process.env.RAZORPAY_KEY_SECRET ?? "")
        .update(rawBody)
        .digest("hex");

      if (expectedSignature !== receivedSignature) {
        console.error("[Razorpay Webhook] ❌ Invalid signature");
        return new Response("Invalid signature", { status: 401 });
      }

      const body = JSON.parse(rawBody);
      const eventType: string = body.event;
      console.log(`[Razorpay Webhook] Received event: ${eventType}`);

      // ── 2. Route to handler ───────────────────────────────────────────────
      if (
        eventType === "payment.captured" ||
        eventType === "payment.authorized" ||
        eventType === "order.paid"
      ) {
        await handlePaymentSuccess(body, eventType);
      } else if (eventType === "payment.failed") {
        await handlePaymentFailed(body);
      } else if (eventType === "refund.created" || eventType === "refund.processed") {
        await handleRefund(body, eventType);
      } else {
        console.log(`[Razorpay Webhook] Unhandled event type: ${eventType}`);
      }

      // Always return 200 — Razorpay retries on non-2xx
      return new Response(JSON.stringify({ received: true }), {
        status: 200,
        headers: { "Content-Type": "application/json" },
      });
    } catch (err: unknown) {
      const errMsg = err instanceof Error ? err.message : "Unknown error";
      console.error("[Razorpay Webhook] Unexpected error:", errMsg);
      // Still return 200 to avoid infinite retries for parsing errors
      return new Response(JSON.stringify({ received: true, error: errMsg }), {
        status: 200,
        headers: { "Content-Type": "application/json" },
      });
    }
  },
});

// ─── Handlers ─────────────────────────────────────────────────────────────────

async function handlePaymentSuccess(body: RazorpayWebhookBody, eventType: string) {
  const payment = body.payload?.payment?.entity ?? body.payload?.order?.entity;
  const razorpayOrderId: string = payment?.order_id ?? "";
  const razorpayPaymentId: string = payment?.id ?? "";
  const amountPaidPaise: number = payment?.amount ?? 0;
  const amountPaid = amountPaidPaise / 100; // Convert paise → INR

  if (!razorpayOrderId) {
    console.error("[Razorpay Webhook] No order_id in payload for event:", eventType);
    return;
  }

  console.log(
    `[Razorpay Webhook] Payment success | Order: ${razorpayOrderId} | Amount: ₹${amountPaid}`,
  );

  // Find booking by razorpay_order_id
  const { data: booking, error: fetchErr } = await supabaseAdmin
    .from("bookings")
    .select("id, booking_id, booking_status, customer_id, total_amount")
    .eq("razorpay_order_id", razorpayOrderId)
    .single();

  if (fetchErr || !booking) {
    console.error("[Razorpay Webhook] Booking not found for order:", razorpayOrderId);
    return;
  }

  // confirmBookingAfterPayment is idempotent — safe to call even if already confirmed
  await confirmBookingAfterPayment(
    {
      bookingId: booking.id,
      orderId: razorpayOrderId,
      paymentId: razorpayPaymentId,
      signature: "", // Signature not available in webhook payload; already verified via header
      amountPaid: amountPaid || (booking.total_amount ?? 0),
      gateway: "razorpay",
      gatewayResponse: body as unknown as Record<string, unknown>,
    },
    supabaseAdmin as unknown as SupabaseClient,
  );

  console.log(`[Razorpay Webhook] ✅ Booking confirmed: ${booking.booking_id}`);

  // Fire-and-forget email
  if (booking.customer_id) {
    const { data: customer } = await supabaseAdmin
      .from("customers")
      .select("name, email")
      .eq("id", booking.customer_id)
      .single();

    if (customer?.email) {
      sendBookingConfirmationEmail({
        customerName: customer.name,
        customerEmail: customer.email,
        bookingId: booking.booking_id ?? booking.id,
        amountPaid: amountPaid || (booking.total_amount ?? 0),
      }).catch((err) => console.error("[Razorpay Webhook] Email failed:", err));
    }
  }
}

async function handlePaymentFailed(body: RazorpayWebhookBody) {
  const payment = body.payload?.payment?.entity;
  const razorpayOrderId: string = payment?.order_id ?? "";
  const razorpayPaymentId: string = payment?.id ?? "";
  const failureReason: string = payment?.error_description ?? "Unknown error";

  if (!razorpayOrderId) {
    console.error("[Razorpay Webhook] No order_id in failed payment payload");
    return;
  }

  console.log(
    `[Razorpay Webhook] Payment failed | Order: ${razorpayOrderId} | Reason: ${failureReason}`,
  );

  const { data: booking, error: fetchErr } = await supabaseAdmin
    .from("bookings")
    .select("id, booking_id, total_amount")
    .eq("razorpay_order_id", razorpayOrderId)
    .single();

  if (fetchErr || !booking) {
    console.error("[Razorpay Webhook] Booking not found for failed order:", razorpayOrderId);
    return;
  }

  // Mark booking as PENDING (not CANCELLED — allow retry)
  await supabaseAdmin
    .from("bookings")
    .update({
      booking_status: "PENDING",
      payment_status: "FAILED",
      updated_at: new Date().toISOString(),
    })
    .eq("id", booking.id);

  // Log failed transaction
  await supabaseAdmin.from("transactions").insert({
    booking_id: booking.id,
    gateway: "razorpay",
    order_id: razorpayOrderId,
    gateway_payment_id: razorpayPaymentId || null,
    amount: booking.total_amount ?? 0,
    currency: "INR",
    status: "FAILED",
    gateway_response: body as unknown as Record<string, unknown>,
  });

  // Timeline event
  await supabaseAdmin.from("booking_timeline").insert({
    booking_id: booking.id,
    event: "PAYMENT_FAILED",
    description: `Payment failed: ${failureReason}`,
    actor: "SYSTEM",
    metadata: { razorpay_order_id: razorpayOrderId, reason: failureReason },
  });

  console.log(`[Razorpay Webhook] ❌ Payment failed for booking: ${booking.booking_id}`);
}

async function handleRefund(body: RazorpayWebhookBody, eventType: string) {
  const refund = body.payload?.refund?.entity;
  const razorpayPaymentId: string = refund?.payment_id ?? "";
  const refundId: string = refund?.id ?? "";
  const refundAmountPaise: number = refund?.amount ?? 0;
  const refundAmount = refundAmountPaise / 100;
  const isProcessed = eventType === "refund.processed";

  if (!razorpayPaymentId) {
    console.error("[Razorpay Webhook] No payment_id in refund payload");
    return;
  }

  console.log(
    `[Razorpay Webhook] Refund ${isProcessed ? "processed" : "created"} | Payment: ${razorpayPaymentId} | Amount: ₹${refundAmount}`,
  );

  // Find booking by razorpay_payment_id
  const { data: booking, error: fetchErr } = await supabaseAdmin
    .from("bookings")
    .select("id, booking_id, customer_id, total_amount, amount_paid")
    .eq("razorpay_payment_id", razorpayPaymentId)
    .single();

  if (fetchErr || !booking) {
    console.warn("[Razorpay Webhook] Booking not found for refund payment:", razorpayPaymentId);
    return;
  }

  // Update payment record
  await supabaseAdmin
    .from("payments")
    .update({
      refund_status: isProcessed ? "REFUNDED" : "PENDING",
      updated_at: new Date().toISOString(),
    })
    .eq("booking_id", booking.id);

  // Update booking refund fields
  await supabaseAdmin
    .from("bookings")
    .update({
      refund_amount: refundAmount,
      refund_status: isProcessed ? "REFUNDED" : "REFUND_INITIATED",
      booking_status: isProcessed ? "REFUNDED" : "REFUND_PENDING",
      updated_at: new Date().toISOString(),
    })
    .eq("id", booking.id);

  // Timeline event
  await supabaseAdmin.from("booking_timeline").insert({
    booking_id: booking.id,
    event: isProcessed ? "REFUND_PROCESSED" : "REFUND_INITIATED",
    description: `Refund of ₹${refundAmount} ${isProcessed ? "processed" : "initiated"} via Razorpay`,
    actor: "SYSTEM",
    metadata: { refund_id: refundId, payment_id: razorpayPaymentId, amount: refundAmount },
  });

  // Admin notification
  await supabaseAdmin.from("notifications").insert({
    recipient_type: "ADMIN",
    title: `💸 Refund ${isProcessed ? "Processed" : "Initiated"}`,
    message: `Refund of ₹${refundAmount.toLocaleString("en-IN")} for booking ${booking.booking_id}`,
    type: "WARNING",
    related_booking_id: booking.id,
  });

  // Update customer total_spent
  if (isProcessed && booking.customer_id) {
    const { data: customer } = await supabaseAdmin
      .from("customers")
      .select("total_spent")
      .eq("id", booking.customer_id)
      .single();

    if (customer) {
      await supabaseAdmin
        .from("customers")
        .update({
          total_spent: Math.max(0, (customer.total_spent ?? 0) - refundAmount),
          updated_at: new Date().toISOString(),
        })
        .eq("id", booking.customer_id);
    }
  }

  console.log(`[Razorpay Webhook] Refund handled for booking: ${booking.booking_id}`);
}
