/**
 * Analytics Tracking API Endpoint
 * POST /api/analytics/track
 *
 * Accepts analytics events from the client and inserts them into
 * the analytics_events Supabase table using the admin client.
 *
 * - Fire-and-forget from client side (sendBeacon)
 * - Gracefully handles missing table / insert errors
 * - Never breaks the client
 * - Insert-only (no read access)
 */

// @ts-expect-error: createAPIFileRoute is dynamically generated by TanStack Start
import { createAPIFileRoute } from "@tanstack/react-start/api";

export const APIRoute = createAPIFileRoute("/api/analytics/track")({
  POST: async ({ request }) => {
    try {
      const body = await request.json();

      const {
        event_name,
        path,
        params,
        session_id,
        device_category,
        browser,
        os,
        screen_size,
        utm_source,
        utm_medium,
        utm_campaign,
        utm_content,
        utm_term,
        referrer,
      } = body;

      // Validate required fields
      if (!event_name || !session_id) {
        return new Response(JSON.stringify({ ok: false, error: "Missing required fields" }), {
          status: 400,
          headers: { "Content-Type": "application/json" },
        });
      }

      // Import supabaseAdmin server-side only
      const { getSupabaseAdmin } = await import("@/lib/supabase-admin");
      const supabaseAdmin = getSupabaseAdmin();

      if (!supabaseAdmin) {
        console.warn("[Analytics Track] supabaseAdmin not available");
        return new Response(JSON.stringify({ ok: true }), {
          status: 200,
          headers: { "Content-Type": "application/json" },
        });
      }

      // Insert event into analytics_events table
      const { error } = await supabaseAdmin.from("analytics_events").insert({
        session_id: String(session_id).slice(0, 255),
        event_name: String(event_name).slice(0, 100),
        path: path ? String(path).slice(0, 500) : null,
        params: params && typeof params === "object" ? params : {},
        device_category: device_category ? String(device_category).slice(0, 20) : null,
        browser: browser ? String(browser).slice(0, 50) : null,
        os: os ? String(os).slice(0, 50) : null,
        screen_size: screen_size ? String(screen_size).slice(0, 20) : null,
        utm_source: utm_source ? String(utm_source).slice(0, 100) : null,
        utm_medium: utm_medium ? String(utm_medium).slice(0, 100) : null,
        utm_campaign: utm_campaign ? String(utm_campaign).slice(0, 200) : null,
        utm_content: utm_content ? String(utm_content).slice(0, 200) : null,
        utm_term: utm_term ? String(utm_term).slice(0, 200) : null,
        referrer: referrer ? String(referrer).slice(0, 500) : null,
      });

      if (error) {
        // Log but don't break — table might not exist yet
        console.warn("[Analytics Track] Insert error (non-fatal):", error.message);
      }

      return new Response(JSON.stringify({ ok: true }), {
        status: 200,
        headers: { "Content-Type": "application/json" },
      });
    } catch (err: any) {
      // Graceful failure — never return 500 to avoid client retries
      console.warn("[Analytics Track] Unexpected error (non-fatal):", err?.message);
      return new Response(JSON.stringify({ ok: true }), {
        status: 200,
        headers: { "Content-Type": "application/json" },
      });
    }
  },
});
