/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CancellationRouteImport } from './routes/cancellation'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as StoriesSlugRouteImport } from './routes/stories_.$slug'
import { Route as JourneysJourneyIdRouteImport } from './routes/journeys/$journeyId'
import { Route as DestinationsSlugRouteImport } from './routes/destinations_.$slug'
import { Route as BookingSuccessRouteImport } from './routes/booking.success'
import { Route as BookJourneyIdRouteImport } from './routes/book.$journeyId'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AdminWebsiteRouteImport } from './routes/admin/website'
import { Route as AdminTripCalendarRouteImport } from './routes/admin/trip-calendar'
import { Route as AdminSuperAdminRouteImport } from './routes/admin/super-admin'
import { Route as AdminStoriesRouteImport } from './routes/admin/stories'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSeatsRouteImport } from './routes/admin/seats'
import { Route as AdminRoomsRouteImport } from './routes/admin/rooms'
import { Route as AdminReviewsRouteImport } from './routes/admin/reviews'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminPackagesRouteImport } from './routes/admin/packages'
import { Route as AdminNotificationsRouteImport } from './routes/admin/notifications'
import { Route as AdminMediaRouteImport } from './routes/admin/media'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminLiveTripsRouteImport } from './routes/admin/live-trips'
import { Route as AdminItineraryPdfsRouteImport } from './routes/admin/itinerary-pdfs'
import { Route as AdminInvoicesRouteImport } from './routes/admin/invoices'
import { Route as AdminInquiriesRouteImport } from './routes/admin/inquiries'
import { Route as AdminHotelsRouteImport } from './routes/admin/hotels'
import { Route as AdminFaqsRouteImport } from './routes/admin/faqs'
import { Route as AdminExpensesRouteImport } from './routes/admin/expenses'
import { Route as AdminEmployeesRouteImport } from './routes/admin/employees'
import { Route as AdminDestinationsRouteImport } from './routes/admin/destinations'
import { Route as AdminDeparturesRouteImport } from './routes/admin/departures'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminCouponsRouteImport } from './routes/admin/coupons'
import { Route as AdminCommunityRouteImport } from './routes/admin/community'
import { Route as AdminBusesRouteImport } from './routes/admin/buses'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'
import { Route as AdminBlogRouteImport } from './routes/admin/blog'
import { Route as AdminBannersRouteImport } from './routes/admin/banners'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminActivityRouteImport } from './routes/admin/activity'
import { Route as AdminWebsiteSectionRouteImport } from './routes/admin/website_.$section'
import { Route as AdminStoriesIdRouteImport } from './routes/admin/stories_.$id'
import { Route as AdminPackagesIdRouteImport } from './routes/admin/packages_.$id'
import { Route as AdminHotelsIdRouteImport } from './routes/admin/hotels_.$id'
import { Route as AdminDestinationsIdRouteImport } from './routes/admin/destinations_.$id'
import { Route as AdminDeparturesIdRouteImport } from './routes/admin/departures_.$id'
import { Route as AdminBusesIdRouteImport } from './routes/admin/buses_.$id'
import { Route as AdminBookingsIdRouteImport } from './routes/admin/bookings_.$id'
import { Route as AdminBlogIdRouteImport } from './routes/admin/blog_.$id'
import { Route as AccountItinerarySlugRouteImport } from './routes/account_.itinerary.$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CancellationRoute = CancellationRouteImport.update({
  id: '/cancellation',
  path: '/cancellation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StoriesSlugRoute = StoriesSlugRouteImport.update({
  id: '/stories_/$slug',
  path: '/stories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneysJourneyIdRoute = JourneysJourneyIdRouteImport.update({
  id: '/journeys/$journeyId',
  path: '/journeys/$journeyId',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsSlugRoute = DestinationsSlugRouteImport.update({
  id: '/destinations_/$slug',
  path: '/destinations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingSuccessRoute = BookingSuccessRouteImport.update({
  id: '/booking/success',
  path: '/booking/success',
  getParentRoute: () => rootRouteImport,
} as any)
const BookJourneyIdRoute = BookJourneyIdRouteImport.update({
  id: '/book/$journeyId',
  path: '/book/$journeyId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWebsiteRoute = AdminWebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTripCalendarRoute = AdminTripCalendarRouteImport.update({
  id: '/trip-calendar',
  path: '/trip-calendar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSuperAdminRoute = AdminSuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStoriesRoute = AdminStoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeatsRoute = AdminSeatsRouteImport.update({
  id: '/seats',
  path: '/seats',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRoomsRoute = AdminRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPackagesRoute = AdminPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLiveTripsRoute = AdminLiveTripsRouteImport.update({
  id: '/live-trips',
  path: '/live-trips',
  getParentRoute: () => AdminRoute,
} as any)
const AdminItineraryPdfsRoute = AdminItineraryPdfsRouteImport.update({
  id: '/itinerary-pdfs',
  path: '/itinerary-pdfs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvoicesRoute = AdminInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInquiriesRoute = AdminInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHotelsRoute = AdminHotelsRouteImport.update({
  id: '/hotels',
  path: '/hotels',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqsRoute = AdminFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExpensesRoute = AdminExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmployeesRoute = AdminEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDestinationsRoute = AdminDestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDeparturesRoute = AdminDeparturesRouteImport.update({
  id: '/departures',
  path: '/departures',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommunityRoute = AdminCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBusesRoute = AdminBusesRouteImport.update({
  id: '/buses',
  path: '/buses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWebsiteSectionRoute = AdminWebsiteSectionRouteImport.update({
  id: '/website_/$section',
  path: '/website/$section',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStoriesIdRoute = AdminStoriesIdRouteImport.update({
  id: '/stories_/$id',
  path: '/stories/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPackagesIdRoute = AdminPackagesIdRouteImport.update({
  id: '/packages_/$id',
  path: '/packages/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHotelsIdRoute = AdminHotelsIdRouteImport.update({
  id: '/hotels_/$id',
  path: '/hotels/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDestinationsIdRoute = AdminDestinationsIdRouteImport.update({
  id: '/destinations_/$id',
  path: '/destinations/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDeparturesIdRoute = AdminDeparturesIdRouteImport.update({
  id: '/departures_/$id',
  path: '/departures/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBusesIdRoute = AdminBusesIdRouteImport.update({
  id: '/buses_/$id',
  path: '/buses/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsIdRoute = AdminBookingsIdRouteImport.update({
  id: '/bookings_/$id',
  path: '/bookings/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogIdRoute = AdminBlogIdRouteImport.update({
  id: '/blog_/$id',
  path: '/blog/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AccountItinerarySlugRoute = AccountItinerarySlugRouteImport.update({
  id: '/account_/itinerary/$slug',
  path: '/account/itinerary/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/cancellation': typeof CancellationRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRoute
  '/explorer': typeof ExplorerRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRoute
  '/terms': typeof TermsRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/buses': typeof AdminBusesRoute
  '/admin/community': typeof AdminCommunityRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/departures': typeof AdminDeparturesRoute
  '/admin/destinations': typeof AdminDestinationsRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/expenses': typeof AdminExpensesRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/hotels': typeof AdminHotelsRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/itinerary-pdfs': typeof AdminItineraryPdfsRoute
  '/admin/live-trips': typeof AdminLiveTripsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/seats': typeof AdminSeatsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stories': typeof AdminStoriesRoute
  '/admin/super-admin': typeof AdminSuperAdminRoute
  '/admin/trip-calendar': typeof AdminTripCalendarRoute
  '/admin/website': typeof AdminWebsiteRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/book/$journeyId': typeof BookJourneyIdRoute
  '/booking/success': typeof BookingSuccessRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/journeys/$journeyId': typeof JourneysJourneyIdRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/account/itinerary/$slug': typeof AccountItinerarySlugRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/bookings/$id': typeof AdminBookingsIdRoute
  '/admin/buses/$id': typeof AdminBusesIdRoute
  '/admin/departures/$id': typeof AdminDeparturesIdRoute
  '/admin/destinations/$id': typeof AdminDestinationsIdRoute
  '/admin/hotels/$id': typeof AdminHotelsIdRoute
  '/admin/packages/$id': typeof AdminPackagesIdRoute
  '/admin/stories/$id': typeof AdminStoriesIdRoute
  '/admin/website/$section': typeof AdminWebsiteSectionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/cancellation': typeof CancellationRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRoute
  '/explorer': typeof ExplorerRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRoute
  '/terms': typeof TermsRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/buses': typeof AdminBusesRoute
  '/admin/community': typeof AdminCommunityRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/departures': typeof AdminDeparturesRoute
  '/admin/destinations': typeof AdminDestinationsRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/expenses': typeof AdminExpensesRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/hotels': typeof AdminHotelsRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/itinerary-pdfs': typeof AdminItineraryPdfsRoute
  '/admin/live-trips': typeof AdminLiveTripsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/seats': typeof AdminSeatsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stories': typeof AdminStoriesRoute
  '/admin/super-admin': typeof AdminSuperAdminRoute
  '/admin/trip-calendar': typeof AdminTripCalendarRoute
  '/admin/website': typeof AdminWebsiteRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/book/$journeyId': typeof BookJourneyIdRoute
  '/booking/success': typeof BookingSuccessRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/journeys/$journeyId': typeof JourneysJourneyIdRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/account/itinerary/$slug': typeof AccountItinerarySlugRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/bookings/$id': typeof AdminBookingsIdRoute
  '/admin/buses/$id': typeof AdminBusesIdRoute
  '/admin/departures/$id': typeof AdminDeparturesIdRoute
  '/admin/destinations/$id': typeof AdminDestinationsIdRoute
  '/admin/hotels/$id': typeof AdminHotelsIdRoute
  '/admin/packages/$id': typeof AdminPackagesIdRoute
  '/admin/stories/$id': typeof AdminStoriesIdRoute
  '/admin/website/$section': typeof AdminWebsiteSectionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/cancellation': typeof CancellationRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRoute
  '/explorer': typeof ExplorerRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRoute
  '/terms': typeof TermsRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/buses': typeof AdminBusesRoute
  '/admin/community': typeof AdminCommunityRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/departures': typeof AdminDeparturesRoute
  '/admin/destinations': typeof AdminDestinationsRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/expenses': typeof AdminExpensesRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/hotels': typeof AdminHotelsRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/itinerary-pdfs': typeof AdminItineraryPdfsRoute
  '/admin/live-trips': typeof AdminLiveTripsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/seats': typeof AdminSeatsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stories': typeof AdminStoriesRoute
  '/admin/super-admin': typeof AdminSuperAdminRoute
  '/admin/trip-calendar': typeof AdminTripCalendarRoute
  '/admin/website': typeof AdminWebsiteRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/book/$journeyId': typeof BookJourneyIdRoute
  '/booking/success': typeof BookingSuccessRoute
  '/destinations_/$slug': typeof DestinationsSlugRoute
  '/journeys/$journeyId': typeof JourneysJourneyIdRoute
  '/stories_/$slug': typeof StoriesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/account_/itinerary/$slug': typeof AccountItinerarySlugRoute
  '/admin/blog_/$id': typeof AdminBlogIdRoute
  '/admin/bookings_/$id': typeof AdminBookingsIdRoute
  '/admin/buses_/$id': typeof AdminBusesIdRoute
  '/admin/departures_/$id': typeof AdminDeparturesIdRoute
  '/admin/destinations_/$id': typeof AdminDestinationsIdRoute
  '/admin/hotels_/$id': typeof AdminHotelsIdRoute
  '/admin/packages_/$id': typeof AdminPackagesIdRoute
  '/admin/stories_/$id': typeof AdminStoriesIdRoute
  '/admin/website_/$section': typeof AdminWebsiteSectionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/about'
    | '/account'
    | '/admin'
    | '/cancellation'
    | '/contact'
    | '/destinations'
    | '/explorer'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/stories'
    | '/terms'
    | '/admin/activity'
    | '/admin/analytics'
    | '/admin/banners'
    | '/admin/blog'
    | '/admin/bookings'
    | '/admin/buses'
    | '/admin/community'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/departures'
    | '/admin/destinations'
    | '/admin/employees'
    | '/admin/expenses'
    | '/admin/faqs'
    | '/admin/hotels'
    | '/admin/inquiries'
    | '/admin/invoices'
    | '/admin/itinerary-pdfs'
    | '/admin/live-trips'
    | '/admin/login'
    | '/admin/media'
    | '/admin/notifications'
    | '/admin/packages'
    | '/admin/payments'
    | '/admin/reviews'
    | '/admin/rooms'
    | '/admin/seats'
    | '/admin/settings'
    | '/admin/stories'
    | '/admin/super-admin'
    | '/admin/trip-calendar'
    | '/admin/website'
    | '/auth/callback'
    | '/book/$journeyId'
    | '/booking/success'
    | '/destinations/$slug'
    | '/journeys/$journeyId'
    | '/stories/$slug'
    | '/admin/'
    | '/account/itinerary/$slug'
    | '/admin/blog/$id'
    | '/admin/bookings/$id'
    | '/admin/buses/$id'
    | '/admin/departures/$id'
    | '/admin/destinations/$id'
    | '/admin/hotels/$id'
    | '/admin/packages/$id'
    | '/admin/stories/$id'
    | '/admin/website/$section'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/about'
    | '/account'
    | '/cancellation'
    | '/contact'
    | '/destinations'
    | '/explorer'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/stories'
    | '/terms'
    | '/admin/activity'
    | '/admin/analytics'
    | '/admin/banners'
    | '/admin/blog'
    | '/admin/bookings'
    | '/admin/buses'
    | '/admin/community'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/departures'
    | '/admin/destinations'
    | '/admin/employees'
    | '/admin/expenses'
    | '/admin/faqs'
    | '/admin/hotels'
    | '/admin/inquiries'
    | '/admin/invoices'
    | '/admin/itinerary-pdfs'
    | '/admin/live-trips'
    | '/admin/login'
    | '/admin/media'
    | '/admin/notifications'
    | '/admin/packages'
    | '/admin/payments'
    | '/admin/reviews'
    | '/admin/rooms'
    | '/admin/seats'
    | '/admin/settings'
    | '/admin/stories'
    | '/admin/super-admin'
    | '/admin/trip-calendar'
    | '/admin/website'
    | '/auth/callback'
    | '/book/$journeyId'
    | '/booking/success'
    | '/destinations/$slug'
    | '/journeys/$journeyId'
    | '/stories/$slug'
    | '/admin'
    | '/account/itinerary/$slug'
    | '/admin/blog/$id'
    | '/admin/bookings/$id'
    | '/admin/buses/$id'
    | '/admin/departures/$id'
    | '/admin/destinations/$id'
    | '/admin/hotels/$id'
    | '/admin/packages/$id'
    | '/admin/stories/$id'
    | '/admin/website/$section'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/about'
    | '/account'
    | '/admin'
    | '/cancellation'
    | '/contact'
    | '/destinations'
    | '/explorer'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/stories'
    | '/terms'
    | '/admin/activity'
    | '/admin/analytics'
    | '/admin/banners'
    | '/admin/blog'
    | '/admin/bookings'
    | '/admin/buses'
    | '/admin/community'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/departures'
    | '/admin/destinations'
    | '/admin/employees'
    | '/admin/expenses'
    | '/admin/faqs'
    | '/admin/hotels'
    | '/admin/inquiries'
    | '/admin/invoices'
    | '/admin/itinerary-pdfs'
    | '/admin/live-trips'
    | '/admin/login'
    | '/admin/media'
    | '/admin/notifications'
    | '/admin/packages'
    | '/admin/payments'
    | '/admin/reviews'
    | '/admin/rooms'
    | '/admin/seats'
    | '/admin/settings'
    | '/admin/stories'
    | '/admin/super-admin'
    | '/admin/trip-calendar'
    | '/admin/website'
    | '/auth/callback'
    | '/book/$journeyId'
    | '/booking/success'
    | '/destinations_/$slug'
    | '/journeys/$journeyId'
    | '/stories_/$slug'
    | '/admin/'
    | '/account_/itinerary/$slug'
    | '/admin/blog_/$id'
    | '/admin/bookings_/$id'
    | '/admin/buses_/$id'
    | '/admin/departures_/$id'
    | '/admin/destinations_/$id'
    | '/admin/hotels_/$id'
    | '/admin/packages_/$id'
    | '/admin/stories_/$id'
    | '/admin/website_/$section'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  CancellationRoute: typeof CancellationRoute
  ContactRoute: typeof ContactRoute
  DestinationsRoute: typeof DestinationsRoute
  ExplorerRoute: typeof ExplorerRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoriesRoute: typeof StoriesRoute
  TermsRoute: typeof TermsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  BookJourneyIdRoute: typeof BookJourneyIdRoute
  BookingSuccessRoute: typeof BookingSuccessRoute
  DestinationsSlugRoute: typeof DestinationsSlugRoute
  JourneysJourneyIdRoute: typeof JourneysJourneyIdRoute
  StoriesSlugRoute: typeof StoriesSlugRoute
  AccountItinerarySlugRoute: typeof AccountItinerarySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancellation': {
      id: '/cancellation'
      path: '/cancellation'
      fullPath: '/cancellation'
      preLoaderRoute: typeof CancellationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/stories_/$slug': {
      id: '/stories_/$slug'
      path: '/stories/$slug'
      fullPath: '/stories/$slug'
      preLoaderRoute: typeof StoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journeys/$journeyId': {
      id: '/journeys/$journeyId'
      path: '/journeys/$journeyId'
      fullPath: '/journeys/$journeyId'
      preLoaderRoute: typeof JourneysJourneyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations_/$slug': {
      id: '/destinations_/$slug'
      path: '/destinations/$slug'
      fullPath: '/destinations/$slug'
      preLoaderRoute: typeof DestinationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/success': {
      id: '/booking/success'
      path: '/booking/success'
      fullPath: '/booking/success'
      preLoaderRoute: typeof BookingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$journeyId': {
      id: '/book/$journeyId'
      path: '/book/$journeyId'
      fullPath: '/book/$journeyId'
      preLoaderRoute: typeof BookJourneyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/website': {
      id: '/admin/website'
      path: '/website'
      fullPath: '/admin/website'
      preLoaderRoute: typeof AdminWebsiteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/trip-calendar': {
      id: '/admin/trip-calendar'
      path: '/trip-calendar'
      fullPath: '/admin/trip-calendar'
      preLoaderRoute: typeof AdminTripCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/super-admin': {
      id: '/admin/super-admin'
      path: '/super-admin'
      fullPath: '/admin/super-admin'
      preLoaderRoute: typeof AdminSuperAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stories': {
      id: '/admin/stories'
      path: '/stories'
      fullPath: '/admin/stories'
      preLoaderRoute: typeof AdminStoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seats': {
      id: '/admin/seats'
      path: '/seats'
      fullPath: '/admin/seats'
      preLoaderRoute: typeof AdminSeatsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rooms': {
      id: '/admin/rooms'
      path: '/rooms'
      fullPath: '/admin/rooms'
      preLoaderRoute: typeof AdminRoomsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/packages': {
      id: '/admin/packages'
      path: '/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AdminPackagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/live-trips': {
      id: '/admin/live-trips'
      path: '/live-trips'
      fullPath: '/admin/live-trips'
      preLoaderRoute: typeof AdminLiveTripsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/itinerary-pdfs': {
      id: '/admin/itinerary-pdfs'
      path: '/itinerary-pdfs'
      fullPath: '/admin/itinerary-pdfs'
      preLoaderRoute: typeof AdminItineraryPdfsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invoices': {
      id: '/admin/invoices'
      path: '/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AdminInvoicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inquiries': {
      id: '/admin/inquiries'
      path: '/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AdminInquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hotels': {
      id: '/admin/hotels'
      path: '/hotels'
      fullPath: '/admin/hotels'
      preLoaderRoute: typeof AdminHotelsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faqs': {
      id: '/admin/faqs'
      path: '/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AdminFaqsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/expenses': {
      id: '/admin/expenses'
      path: '/expenses'
      fullPath: '/admin/expenses'
      preLoaderRoute: typeof AdminExpensesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/employees': {
      id: '/admin/employees'
      path: '/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminEmployeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/destinations': {
      id: '/admin/destinations'
      path: '/destinations'
      fullPath: '/admin/destinations'
      preLoaderRoute: typeof AdminDestinationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/departures': {
      id: '/admin/departures'
      path: '/departures'
      fullPath: '/admin/departures'
      preLoaderRoute: typeof AdminDeparturesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/community': {
      id: '/admin/community'
      path: '/community'
      fullPath: '/admin/community'
      preLoaderRoute: typeof AdminCommunityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/buses': {
      id: '/admin/buses'
      path: '/buses'
      fullPath: '/admin/buses'
      preLoaderRoute: typeof AdminBusesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/website_/$section': {
      id: '/admin/website_/$section'
      path: '/website/$section'
      fullPath: '/admin/website/$section'
      preLoaderRoute: typeof AdminWebsiteSectionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stories_/$id': {
      id: '/admin/stories_/$id'
      path: '/stories/$id'
      fullPath: '/admin/stories/$id'
      preLoaderRoute: typeof AdminStoriesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/packages_/$id': {
      id: '/admin/packages_/$id'
      path: '/packages/$id'
      fullPath: '/admin/packages/$id'
      preLoaderRoute: typeof AdminPackagesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hotels_/$id': {
      id: '/admin/hotels_/$id'
      path: '/hotels/$id'
      fullPath: '/admin/hotels/$id'
      preLoaderRoute: typeof AdminHotelsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/destinations_/$id': {
      id: '/admin/destinations_/$id'
      path: '/destinations/$id'
      fullPath: '/admin/destinations/$id'
      preLoaderRoute: typeof AdminDestinationsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/departures_/$id': {
      id: '/admin/departures_/$id'
      path: '/departures/$id'
      fullPath: '/admin/departures/$id'
      preLoaderRoute: typeof AdminDeparturesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/buses_/$id': {
      id: '/admin/buses_/$id'
      path: '/buses/$id'
      fullPath: '/admin/buses/$id'
      preLoaderRoute: typeof AdminBusesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings_/$id': {
      id: '/admin/bookings_/$id'
      path: '/bookings/$id'
      fullPath: '/admin/bookings/$id'
      preLoaderRoute: typeof AdminBookingsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog_/$id': {
      id: '/admin/blog_/$id'
      path: '/blog/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AdminBlogIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account_/itinerary/$slug': {
      id: '/account_/itinerary/$slug'
      path: '/account/itinerary/$slug'
      fullPath: '/account/itinerary/$slug'
      preLoaderRoute: typeof AccountItinerarySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminActivityRoute: typeof AdminActivityRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBannersRoute: typeof AdminBannersRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminBusesRoute: typeof AdminBusesRoute
  AdminCommunityRoute: typeof AdminCommunityRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDeparturesRoute: typeof AdminDeparturesRoute
  AdminDestinationsRoute: typeof AdminDestinationsRoute
  AdminEmployeesRoute: typeof AdminEmployeesRoute
  AdminExpensesRoute: typeof AdminExpensesRoute
  AdminFaqsRoute: typeof AdminFaqsRoute
  AdminHotelsRoute: typeof AdminHotelsRoute
  AdminInquiriesRoute: typeof AdminInquiriesRoute
  AdminInvoicesRoute: typeof AdminInvoicesRoute
  AdminItineraryPdfsRoute: typeof AdminItineraryPdfsRoute
  AdminLiveTripsRoute: typeof AdminLiveTripsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPackagesRoute: typeof AdminPackagesRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminRoomsRoute: typeof AdminRoomsRoute
  AdminSeatsRoute: typeof AdminSeatsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStoriesRoute: typeof AdminStoriesRoute
  AdminSuperAdminRoute: typeof AdminSuperAdminRoute
  AdminTripCalendarRoute: typeof AdminTripCalendarRoute
  AdminWebsiteRoute: typeof AdminWebsiteRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBlogIdRoute: typeof AdminBlogIdRoute
  AdminBookingsIdRoute: typeof AdminBookingsIdRoute
  AdminBusesIdRoute: typeof AdminBusesIdRoute
  AdminDeparturesIdRoute: typeof AdminDeparturesIdRoute
  AdminDestinationsIdRoute: typeof AdminDestinationsIdRoute
  AdminHotelsIdRoute: typeof AdminHotelsIdRoute
  AdminPackagesIdRoute: typeof AdminPackagesIdRoute
  AdminStoriesIdRoute: typeof AdminStoriesIdRoute
  AdminWebsiteSectionRoute: typeof AdminWebsiteSectionRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityRoute: AdminActivityRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBannersRoute: AdminBannersRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminBusesRoute: AdminBusesRoute,
  AdminCommunityRoute: AdminCommunityRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDeparturesRoute: AdminDeparturesRoute,
  AdminDestinationsRoute: AdminDestinationsRoute,
  AdminEmployeesRoute: AdminEmployeesRoute,
  AdminExpensesRoute: AdminExpensesRoute,
  AdminFaqsRoute: AdminFaqsRoute,
  AdminHotelsRoute: AdminHotelsRoute,
  AdminInquiriesRoute: AdminInquiriesRoute,
  AdminInvoicesRoute: AdminInvoicesRoute,
  AdminItineraryPdfsRoute: AdminItineraryPdfsRoute,
  AdminLiveTripsRoute: AdminLiveTripsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPackagesRoute: AdminPackagesRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminRoomsRoute: AdminRoomsRoute,
  AdminSeatsRoute: AdminSeatsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStoriesRoute: AdminStoriesRoute,
  AdminSuperAdminRoute: AdminSuperAdminRoute,
  AdminTripCalendarRoute: AdminTripCalendarRoute,
  AdminWebsiteRoute: AdminWebsiteRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBlogIdRoute: AdminBlogIdRoute,
  AdminBookingsIdRoute: AdminBookingsIdRoute,
  AdminBusesIdRoute: AdminBusesIdRoute,
  AdminDeparturesIdRoute: AdminDeparturesIdRoute,
  AdminDestinationsIdRoute: AdminDestinationsIdRoute,
  AdminHotelsIdRoute: AdminHotelsIdRoute,
  AdminPackagesIdRoute: AdminPackagesIdRoute,
  AdminStoriesIdRoute: AdminStoriesIdRoute,
  AdminWebsiteSectionRoute: AdminWebsiteSectionRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  CancellationRoute: CancellationRoute,
  ContactRoute: ContactRoute,
  DestinationsRoute: DestinationsRoute,
  ExplorerRoute: ExplorerRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoriesRoute: StoriesRoute,
  TermsRoute: TermsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  BookJourneyIdRoute: BookJourneyIdRoute,
  BookingSuccessRoute: BookingSuccessRoute,
  DestinationsSlugRoute: DestinationsSlugRoute,
  JourneysJourneyIdRoute: JourneysJourneyIdRoute,
  StoriesSlugRoute: StoriesSlugRoute,
  AccountItinerarySlugRoute: AccountItinerarySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
