/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UdaipurRouteImport } from './routes/udaipur'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as McleodganjRouteImport } from './routes/mcleodganj'
import { Route as ManaliRouteImport } from './routes/manali'
import { Route as JibhiRouteImport } from './routes/jibhi'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChoptaTungnathRouteImport } from './routes/chopta-tungnath'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as JourneysJourneyIdRouteImport } from './routes/journeys/$journeyId'
import { Route as BookJourneyIdRouteImport } from './routes/book.$journeyId'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSeatsRouteImport } from './routes/admin/seats'
import { Route as AdminRoomsRouteImport } from './routes/admin/rooms'
import { Route as AdminReviewsRouteImport } from './routes/admin/reviews'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminPackagesRouteImport } from './routes/admin/packages'
import { Route as AdminNotificationsRouteImport } from './routes/admin/notifications'
import { Route as AdminMediaRouteImport } from './routes/admin/media'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminInquiriesRouteImport } from './routes/admin/inquiries'
import { Route as AdminHotelsRouteImport } from './routes/admin/hotels'
import { Route as AdminDestinationsRouteImport } from './routes/admin/destinations'
import { Route as AdminDeparturesRouteImport } from './routes/admin/departures'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminCouponsRouteImport } from './routes/admin/coupons'
import { Route as AdminBusesRouteImport } from './routes/admin/buses'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'
import { Route as AdminBlogRouteImport } from './routes/admin/blog'
import { Route as AdminBannersRouteImport } from './routes/admin/banners'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminActivityRouteImport } from './routes/admin/activity'
import { Route as AdminPackagesIdRouteImport } from './routes/admin/packages_.$id'
import { Route as AdminHotelsIdRouteImport } from './routes/admin/hotels_.$id'
import { Route as AdminDestinationsIdRouteImport } from './routes/admin/destinations_.$id'
import { Route as AdminDeparturesIdRouteImport } from './routes/admin/departures_.$id'
import { Route as AdminBusesIdRouteImport } from './routes/admin/buses_.$id'
import { Route as AdminBookingsIdRouteImport } from './routes/admin/bookings_.$id'
import { Route as AdminBlogIdRouteImport } from './routes/admin/blog_.$id'

const UdaipurRoute = UdaipurRouteImport.update({
  id: '/udaipur',
  path: '/udaipur',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const McleodganjRoute = McleodganjRouteImport.update({
  id: '/mcleodganj',
  path: '/mcleodganj',
  getParentRoute: () => rootRouteImport,
} as any)
const ManaliRoute = ManaliRouteImport.update({
  id: '/manali',
  path: '/manali',
  getParentRoute: () => rootRouteImport,
} as any)
const JibhiRoute = JibhiRouteImport.update({
  id: '/jibhi',
  path: '/jibhi',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChoptaTungnathRoute = ChoptaTungnathRouteImport.update({
  id: '/chopta-tungnath',
  path: '/chopta-tungnath',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const JourneysJourneyIdRoute = JourneysJourneyIdRouteImport.update({
  id: '/journeys/$journeyId',
  path: '/journeys/$journeyId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookJourneyIdRoute = BookJourneyIdRouteImport.update({
  id: '/book/$journeyId',
  path: '/book/$journeyId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeatsRoute = AdminSeatsRouteImport.update({
  id: '/seats',
  path: '/seats',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRoomsRoute = AdminRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPackagesRoute = AdminPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInquiriesRoute = AdminInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHotelsRoute = AdminHotelsRouteImport.update({
  id: '/hotels',
  path: '/hotels',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDestinationsRoute = AdminDestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDeparturesRoute = AdminDeparturesRouteImport.update({
  id: '/departures',
  path: '/departures',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBusesRoute = AdminBusesRouteImport.update({
  id: '/buses',
  path: '/buses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPackagesIdRoute = AdminPackagesIdRouteImport.update({
  id: '/packages_/$id',
  path: '/packages/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHotelsIdRoute = AdminHotelsIdRouteImport.update({
  id: '/hotels_/$id',
  path: '/hotels/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDestinationsIdRoute = AdminDestinationsIdRouteImport.update({
  id: '/destinations_/$id',
  path: '/destinations/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDeparturesIdRoute = AdminDeparturesIdRouteImport.update({
  id: '/departures_/$id',
  path: '/departures/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBusesIdRoute = AdminBusesIdRouteImport.update({
  id: '/buses_/$id',
  path: '/buses/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsIdRoute = AdminBookingsIdRouteImport.update({
  id: '/bookings_/$id',
  path: '/bookings/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogIdRoute = AdminBlogIdRouteImport.update({
  id: '/blog_/$id',
  path: '/blog/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/chopta-tungnath': typeof ChoptaTungnathRoute
  '/contact': typeof ContactRoute
  '/jibhi': typeof JibhiRoute
  '/manali': typeof ManaliRoute
  '/mcleodganj': typeof McleodganjRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRoute
  '/udaipur': typeof UdaipurRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/buses': typeof AdminBusesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/departures': typeof AdminDeparturesRoute
  '/admin/destinations': typeof AdminDestinationsRoute
  '/admin/hotels': typeof AdminHotelsRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/seats': typeof AdminSeatsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/book/$journeyId': typeof BookJourneyIdRoute
  '/journeys/$journeyId': typeof JourneysJourneyIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/bookings/$id': typeof AdminBookingsIdRoute
  '/admin/buses/$id': typeof AdminBusesIdRoute
  '/admin/departures/$id': typeof AdminDeparturesIdRoute
  '/admin/destinations/$id': typeof AdminDestinationsIdRoute
  '/admin/hotels/$id': typeof AdminHotelsIdRoute
  '/admin/packages/$id': typeof AdminPackagesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/chopta-tungnath': typeof ChoptaTungnathRoute
  '/contact': typeof ContactRoute
  '/jibhi': typeof JibhiRoute
  '/manali': typeof ManaliRoute
  '/mcleodganj': typeof McleodganjRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRoute
  '/udaipur': typeof UdaipurRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/buses': typeof AdminBusesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/departures': typeof AdminDeparturesRoute
  '/admin/destinations': typeof AdminDestinationsRoute
  '/admin/hotels': typeof AdminHotelsRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/seats': typeof AdminSeatsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/book/$journeyId': typeof BookJourneyIdRoute
  '/journeys/$journeyId': typeof JourneysJourneyIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/bookings/$id': typeof AdminBookingsIdRoute
  '/admin/buses/$id': typeof AdminBusesIdRoute
  '/admin/departures/$id': typeof AdminDeparturesIdRoute
  '/admin/destinations/$id': typeof AdminDestinationsIdRoute
  '/admin/hotels/$id': typeof AdminHotelsIdRoute
  '/admin/packages/$id': typeof AdminPackagesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/chopta-tungnath': typeof ChoptaTungnathRoute
  '/contact': typeof ContactRoute
  '/jibhi': typeof JibhiRoute
  '/manali': typeof ManaliRoute
  '/mcleodganj': typeof McleodganjRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRoute
  '/udaipur': typeof UdaipurRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/buses': typeof AdminBusesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/departures': typeof AdminDeparturesRoute
  '/admin/destinations': typeof AdminDestinationsRoute
  '/admin/hotels': typeof AdminHotelsRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/seats': typeof AdminSeatsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/book/$journeyId': typeof BookJourneyIdRoute
  '/journeys/$journeyId': typeof JourneysJourneyIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/blog_/$id': typeof AdminBlogIdRoute
  '/admin/bookings_/$id': typeof AdminBookingsIdRoute
  '/admin/buses_/$id': typeof AdminBusesIdRoute
  '/admin/departures_/$id': typeof AdminDeparturesIdRoute
  '/admin/destinations_/$id': typeof AdminDestinationsIdRoute
  '/admin/hotels_/$id': typeof AdminHotelsIdRoute
  '/admin/packages_/$id': typeof AdminPackagesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/chopta-tungnath'
    | '/contact'
    | '/jibhi'
    | '/manali'
    | '/mcleodganj'
    | '/sitemap.xml'
    | '/stories'
    | '/udaipur'
    | '/admin/activity'
    | '/admin/analytics'
    | '/admin/banners'
    | '/admin/blog'
    | '/admin/bookings'
    | '/admin/buses'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/departures'
    | '/admin/destinations'
    | '/admin/hotels'
    | '/admin/inquiries'
    | '/admin/login'
    | '/admin/media'
    | '/admin/notifications'
    | '/admin/packages'
    | '/admin/payments'
    | '/admin/reviews'
    | '/admin/rooms'
    | '/admin/seats'
    | '/admin/settings'
    | '/book/$journeyId'
    | '/journeys/$journeyId'
    | '/admin/'
    | '/admin/blog/$id'
    | '/admin/bookings/$id'
    | '/admin/buses/$id'
    | '/admin/departures/$id'
    | '/admin/destinations/$id'
    | '/admin/hotels/$id'
    | '/admin/packages/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/chopta-tungnath'
    | '/contact'
    | '/jibhi'
    | '/manali'
    | '/mcleodganj'
    | '/sitemap.xml'
    | '/stories'
    | '/udaipur'
    | '/admin/activity'
    | '/admin/analytics'
    | '/admin/banners'
    | '/admin/blog'
    | '/admin/bookings'
    | '/admin/buses'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/departures'
    | '/admin/destinations'
    | '/admin/hotels'
    | '/admin/inquiries'
    | '/admin/login'
    | '/admin/media'
    | '/admin/notifications'
    | '/admin/packages'
    | '/admin/payments'
    | '/admin/reviews'
    | '/admin/rooms'
    | '/admin/seats'
    | '/admin/settings'
    | '/book/$journeyId'
    | '/journeys/$journeyId'
    | '/admin'
    | '/admin/blog/$id'
    | '/admin/bookings/$id'
    | '/admin/buses/$id'
    | '/admin/departures/$id'
    | '/admin/destinations/$id'
    | '/admin/hotels/$id'
    | '/admin/packages/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/chopta-tungnath'
    | '/contact'
    | '/jibhi'
    | '/manali'
    | '/mcleodganj'
    | '/sitemap.xml'
    | '/stories'
    | '/udaipur'
    | '/admin/activity'
    | '/admin/analytics'
    | '/admin/banners'
    | '/admin/blog'
    | '/admin/bookings'
    | '/admin/buses'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/departures'
    | '/admin/destinations'
    | '/admin/hotels'
    | '/admin/inquiries'
    | '/admin/login'
    | '/admin/media'
    | '/admin/notifications'
    | '/admin/packages'
    | '/admin/payments'
    | '/admin/reviews'
    | '/admin/rooms'
    | '/admin/seats'
    | '/admin/settings'
    | '/book/$journeyId'
    | '/journeys/$journeyId'
    | '/admin/'
    | '/admin/blog_/$id'
    | '/admin/bookings_/$id'
    | '/admin/buses_/$id'
    | '/admin/departures_/$id'
    | '/admin/destinations_/$id'
    | '/admin/hotels_/$id'
    | '/admin/packages_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  ChoptaTungnathRoute: typeof ChoptaTungnathRoute
  ContactRoute: typeof ContactRoute
  JibhiRoute: typeof JibhiRoute
  ManaliRoute: typeof ManaliRoute
  McleodganjRoute: typeof McleodganjRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoriesRoute: typeof StoriesRoute
  UdaipurRoute: typeof UdaipurRoute
  BookJourneyIdRoute: typeof BookJourneyIdRoute
  JourneysJourneyIdRoute: typeof JourneysJourneyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/udaipur': {
      id: '/udaipur'
      path: '/udaipur'
      fullPath: '/udaipur'
      preLoaderRoute: typeof UdaipurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcleodganj': {
      id: '/mcleodganj'
      path: '/mcleodganj'
      fullPath: '/mcleodganj'
      preLoaderRoute: typeof McleodganjRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manali': {
      id: '/manali'
      path: '/manali'
      fullPath: '/manali'
      preLoaderRoute: typeof ManaliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jibhi': {
      id: '/jibhi'
      path: '/jibhi'
      fullPath: '/jibhi'
      preLoaderRoute: typeof JibhiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chopta-tungnath': {
      id: '/chopta-tungnath'
      path: '/chopta-tungnath'
      fullPath: '/chopta-tungnath'
      preLoaderRoute: typeof ChoptaTungnathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/journeys/$journeyId': {
      id: '/journeys/$journeyId'
      path: '/journeys/$journeyId'
      fullPath: '/journeys/$journeyId'
      preLoaderRoute: typeof JourneysJourneyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$journeyId': {
      id: '/book/$journeyId'
      path: '/book/$journeyId'
      fullPath: '/book/$journeyId'
      preLoaderRoute: typeof BookJourneyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seats': {
      id: '/admin/seats'
      path: '/seats'
      fullPath: '/admin/seats'
      preLoaderRoute: typeof AdminSeatsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rooms': {
      id: '/admin/rooms'
      path: '/rooms'
      fullPath: '/admin/rooms'
      preLoaderRoute: typeof AdminRoomsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/packages': {
      id: '/admin/packages'
      path: '/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AdminPackagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inquiries': {
      id: '/admin/inquiries'
      path: '/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AdminInquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hotels': {
      id: '/admin/hotels'
      path: '/hotels'
      fullPath: '/admin/hotels'
      preLoaderRoute: typeof AdminHotelsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/destinations': {
      id: '/admin/destinations'
      path: '/destinations'
      fullPath: '/admin/destinations'
      preLoaderRoute: typeof AdminDestinationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/departures': {
      id: '/admin/departures'
      path: '/departures'
      fullPath: '/admin/departures'
      preLoaderRoute: typeof AdminDeparturesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/buses': {
      id: '/admin/buses'
      path: '/buses'
      fullPath: '/admin/buses'
      preLoaderRoute: typeof AdminBusesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/packages_/$id': {
      id: '/admin/packages_/$id'
      path: '/packages/$id'
      fullPath: '/admin/packages/$id'
      preLoaderRoute: typeof AdminPackagesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hotels_/$id': {
      id: '/admin/hotels_/$id'
      path: '/hotels/$id'
      fullPath: '/admin/hotels/$id'
      preLoaderRoute: typeof AdminHotelsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/destinations_/$id': {
      id: '/admin/destinations_/$id'
      path: '/destinations/$id'
      fullPath: '/admin/destinations/$id'
      preLoaderRoute: typeof AdminDestinationsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/departures_/$id': {
      id: '/admin/departures_/$id'
      path: '/departures/$id'
      fullPath: '/admin/departures/$id'
      preLoaderRoute: typeof AdminDeparturesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/buses_/$id': {
      id: '/admin/buses_/$id'
      path: '/buses/$id'
      fullPath: '/admin/buses/$id'
      preLoaderRoute: typeof AdminBusesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings_/$id': {
      id: '/admin/bookings_/$id'
      path: '/bookings/$id'
      fullPath: '/admin/bookings/$id'
      preLoaderRoute: typeof AdminBookingsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog_/$id': {
      id: '/admin/blog_/$id'
      path: '/blog/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AdminBlogIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminActivityRoute: typeof AdminActivityRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBannersRoute: typeof AdminBannersRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminBusesRoute: typeof AdminBusesRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDeparturesRoute: typeof AdminDeparturesRoute
  AdminDestinationsRoute: typeof AdminDestinationsRoute
  AdminHotelsRoute: typeof AdminHotelsRoute
  AdminInquiriesRoute: typeof AdminInquiriesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPackagesRoute: typeof AdminPackagesRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminRoomsRoute: typeof AdminRoomsRoute
  AdminSeatsRoute: typeof AdminSeatsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBlogIdRoute: typeof AdminBlogIdRoute
  AdminBookingsIdRoute: typeof AdminBookingsIdRoute
  AdminBusesIdRoute: typeof AdminBusesIdRoute
  AdminDeparturesIdRoute: typeof AdminDeparturesIdRoute
  AdminDestinationsIdRoute: typeof AdminDestinationsIdRoute
  AdminHotelsIdRoute: typeof AdminHotelsIdRoute
  AdminPackagesIdRoute: typeof AdminPackagesIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityRoute: AdminActivityRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBannersRoute: AdminBannersRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminBusesRoute: AdminBusesRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDeparturesRoute: AdminDeparturesRoute,
  AdminDestinationsRoute: AdminDestinationsRoute,
  AdminHotelsRoute: AdminHotelsRoute,
  AdminInquiriesRoute: AdminInquiriesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPackagesRoute: AdminPackagesRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminRoomsRoute: AdminRoomsRoute,
  AdminSeatsRoute: AdminSeatsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBlogIdRoute: AdminBlogIdRoute,
  AdminBookingsIdRoute: AdminBookingsIdRoute,
  AdminBusesIdRoute: AdminBusesIdRoute,
  AdminDeparturesIdRoute: AdminDeparturesIdRoute,
  AdminDestinationsIdRoute: AdminDestinationsIdRoute,
  AdminHotelsIdRoute: AdminHotelsIdRoute,
  AdminPackagesIdRoute: AdminPackagesIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  ChoptaTungnathRoute: ChoptaTungnathRoute,
  ContactRoute: ContactRoute,
  JibhiRoute: JibhiRoute,
  ManaliRoute: ManaliRoute,
  McleodganjRoute: McleodganjRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoriesRoute: StoriesRoute,
  UdaipurRoute: UdaipurRoute,
  BookJourneyIdRoute: BookJourneyIdRoute,
  JourneysJourneyIdRoute: JourneysJourneyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
