// @ts-expect-error: createAPIFileRoute is dynamically generated by TanStack Start
import { createAPIFileRoute } from "@tanstack/react-start/api";
import { getSupabaseAdmin } from "@/lib/supabase-admin";

export const APIRoute = createAPIFileRoute("/api/admin/blog")({
  POST: async ({ request }) => {
    try {
      const body = await request.json().catch(() => ({}));
      const { action, id, payload } = body;

      const adminClient = getSupabaseAdmin();
      if (!adminClient) {
        return new Response(
          JSON.stringify({
            success: false,
            error: { message: "Server Admin client unavailable. SUPABASE_SERVICE_ROLE_KEY missing on server." }
          }),
          { status: 500, headers: { "Content-Type": "application/json" } }
        );
      }

      // ----------------------------------------------------
      // 1. CREATE BLOG (INSERT)
      // ----------------------------------------------------
      if (action === "create" || !action) {
        const blogData = payload || body;
        if (!blogData.title || !String(blogData.title).trim()) {
          return new Response(
            JSON.stringify({ success: false, error: { message: "Article title is required" } }),
            { status: 400, headers: { "Content-Type": "application/json" } }
          );
        }
        if (!blogData.slug || !String(blogData.slug).trim()) {
          return new Response(
            JSON.stringify({ success: false, error: { message: "Slug URL is required" } }),
            { status: 400, headers: { "Content-Type": "application/json" } }
          );
        }
        if (!blogData.content || !String(blogData.content).trim()) {
          return new Response(
            JSON.stringify({ success: false, error: { message: "Content body is required" } }),
            { status: 400, headers: { "Content-Type": "application/json" } }
          );
        }

        // Merge author_image into seo JSONB (blogs table has no author_image column)
        const existingSeo = typeof blogData.seo === 'object' && blogData.seo !== null ? blogData.seo : {};
        const mergedSeo = {
          ...existingSeo,
          ...(blogData.seo_title ? { title: blogData.seo_title } : {}),
          ...(blogData.seo_description ? { description: blogData.seo_description } : {}),
          author_image: blogData.author_image || existingSeo.author_image || null,
        };

        const cleanPayload = {
          title: String(blogData.title).trim(),
          slug: String(blogData.slug).trim().toLowerCase(),
          content: String(blogData.content).trim(),
          excerpt: blogData.excerpt ? String(blogData.excerpt).trim() : null,
          featured_image: blogData.featured_image || blogData.cover_image || null,
          category: blogData.category || "SOLO TRAVEL",
          gallery: Array.isArray(blogData.gallery) ? blogData.gallery : [],
          tags: Array.isArray(blogData.tags) ? blogData.tags : null,
          author_id: blogData.author_id || null,
          author_name: blogData.author_name || "Nomadik Admin",
          destination_id: blogData.destination_id || null,
          journey_id: blogData.journey_id || null,
          seo: mergedSeo,
          is_published: Boolean(blogData.is_published),
          is_featured: Boolean(blogData.is_featured),
          published_at: blogData.is_published
            ? (blogData.published_at || new Date().toISOString())
            : (blogData.published_at || null),
          updated_at: new Date().toISOString(),
        };

        const { data, error } = await adminClient
          .from("blogs")
          .insert(cleanPayload)
          .select("*")
          .single();

        if (error) {
          console.error("[API /api/admin/blog POST Insert Error]:", error);
          return new Response(
            JSON.stringify({
              success: false,
              error: {
                message: error.message,
                details: error.details,
                hint: error.hint,
                code: error.code,
              },
            }),
            { status: 400, headers: { "Content-Type": "application/json" } }
          );
        }

        return new Response(
          JSON.stringify({ success: true, data }),
          { status: 200, headers: { "Content-Type": "application/json" } }
        );
      }

      // ----------------------------------------------------
      // 2. UPDATE BLOG
      // ----------------------------------------------------
      if (action === "update") {
        if (!id) {
          return new Response(
            JSON.stringify({ success: false, error: { message: "Blog ID is required for update" } }),
            { status: 400, headers: { "Content-Type": "application/json" } }
          );
        }

        // Merge author_image into seo JSONB for update (blogs table has no author_image column)
        const existingUpdateSeo = typeof payload?.seo === 'object' && payload?.seo !== null ? payload.seo : {};
        const mergedUpdateSeo = {
          ...existingUpdateSeo,
          author_image: payload?.author_image || existingUpdateSeo.author_image || null,
        };

        const cleanPayload: Record<string, any> = {
          ...payload,
          seo: mergedUpdateSeo,
          updated_at: new Date().toISOString(),
        };

        // Remove non-existent columns from payload
        delete cleanPayload.author_image;
        delete cleanPayload.cover_image;
        delete cleanPayload.seo_title;
        delete cleanPayload.seo_description;

        if (payload?.title) cleanPayload.title = String(payload.title).trim();
        if (payload?.slug) cleanPayload.slug = String(payload.slug).trim().toLowerCase();
        if (payload?.content) cleanPayload.content = String(payload.content).trim();
        if (payload?.is_published !== undefined) {
          cleanPayload.published_at = payload.is_published
            ? (payload.published_at || new Date().toISOString())
            : payload.published_at;
        }

        const { data, error } = await adminClient
          .from("blogs")
          .update(cleanPayload)
          .eq("id", id)
          .select("*")
          .single();

        if (error) {
          console.error("[API /api/admin/blog POST Update Error]:", error);
          return new Response(
            JSON.stringify({
              success: false,
              error: {
                message: error.message,
                details: error.details,
                hint: error.hint,
                code: error.code,
              },
            }),
            { status: 400, headers: { "Content-Type": "application/json" } }
          );
        }

        return new Response(
          JSON.stringify({ success: true, data }),
          { status: 200, headers: { "Content-Type": "application/json" } }
        );
      }

      // ----------------------------------------------------
      // 3. DELETE BLOG
      // ----------------------------------------------------
      if (action === "delete") {
        if (!id) {
          return new Response(
            JSON.stringify({ success: false, error: { message: "Blog ID is required for deletion" } }),
            { status: 400, headers: { "Content-Type": "application/json" } }
          );
        }

        const { error } = await adminClient.from("blogs").delete().eq("id", id);
        if (error) {
          console.error("[API /api/admin/blog POST Delete Error]:", error);
          return new Response(
            JSON.stringify({
              success: false,
              error: {
                message: error.message,
                details: error.details,
                hint: error.hint,
                code: error.code,
              },
            }),
            { status: 400, headers: { "Content-Type": "application/json" } }
          );
        }

        return new Response(
          JSON.stringify({ success: true }),
          { status: 200, headers: { "Content-Type": "application/json" } }
        );
      }

      return new Response(
        JSON.stringify({ success: false, error: { message: `Unknown action: ${action}` } }),
        { status: 400, headers: { "Content-Type": "application/json" } }
      );
    } catch (err: any) {
      console.error("[API /api/admin/blog Unexpected Error]:", err);
      return new Response(
        JSON.stringify({
          success: false,
          error: { message: err?.message || "Unexpected server error" },
        }),
        { status: 500, headers: { "Content-Type": "application/json" } }
      );
    }
  },
});
